<Project>

  <!--
    Copyright Subatomix Research Inc.
    SPDX-License-Identifier: MIT
  -->

  <!--
    * Imported late: project -> SDK .targets -> NuGet package .targets -> this
    * Override properties and targets here.
    https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build
  -->

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None Include="..\icon.png" LinkBase="Properties"
          Pack="true" PackagePath="" CopyToOutputDirectory="Never" />
    <None Include="..\LICENSE.txt" LinkBase="Properties"
          Pack="true" PackagePath="" CopyToOutputDirectory="Never" />
    <None Include="..\README.md" LinkBase="Properties"
          Pack="true" PackagePath="" CopyToOutputDirectory="Never" />
  </ItemGroup>

  <!-- Versioning -->
  <ItemGroup>
    <PackageReference Include="Subatomix.Build.Versioning.Semantic"
                      Version="1.1.0" PrivateAssets="all" />
  </ItemGroup>

  <!-- Visibility -->
  <ItemGroup>
    <InternalsVisibleTo Include="Subatomix.Build.Packaging.PowerShellModule.Tests" />
  </ItemGroup>

  <!-- Print source paths of packaged files -->
  <PropertyGroup>
    <PackDependsOn>$(PackDependsOn);PrintPackageFiles</PackDependsOn>
  </PropertyGroup>
  <Target Name="PrintPackageFiles" Condition="'$(IsPackable)' == 'true'">
    <ItemGroup>
      <_BuildOutputInPackage PrettyPath="$(BuildOutputTargetFolder)\%(TargetFramework)\%(TargetPath)" />
      <_BuildOutputInPackage PrettyPath="$([MSBuild]::NormalizePath('%(PrettyPath)'))" />
      <_BuildOutputInPackage PrettyPath="$([MSBuild]::MakeRelative('.', '%(PrettyPath)'))" />
      <_PackageFilesToPrint Include="@(_BuildOutputInPackage->'%(PrettyPath)')" />
      <_PackageFilesToPrint Include="@(_PackageFiles->'%(RecursiveDir)%(Filename)%(Extension)')" />
    </ItemGroup>
    <Message Importance="high" Text="Packed: $(PackageId) &lt;- %(_PackageFilesToPrint.Identity)" />
  </Target>

</Project>
